name: Build Windows (LegionGames)

on:
  push:
    branches: [master, legion-pairing-fix]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: Windows-AMD64
    runs-on: windows-2022
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: ucrt64
          update: true
          install: >-
            wget

      - name: Install build dependencies
        env:
          TOOLCHAIN: ucrt-x86_64
        shell: msys2 {0}
        run: |
          declare -A pinned_deps
          dependencies=(
            "git"
            "mingw-w64-${TOOLCHAIN}-boost"
            "mingw-w64-${TOOLCHAIN}-cmake"
            "mingw-w64-${TOOLCHAIN}-cppwinrt"
            "mingw-w64-${TOOLCHAIN}-curl-winssl"
            "mingw-w64-${TOOLCHAIN}-gcc"
            "mingw-w64-${TOOLCHAIN}-graphviz"
            "mingw-w64-${TOOLCHAIN}-miniupnpc"
            "mingw-w64-${TOOLCHAIN}-nlohmann-json"
            "mingw-w64-${TOOLCHAIN}-onevpl"
            "mingw-w64-${TOOLCHAIN}-openssl"
            "mingw-w64-${TOOLCHAIN}-opus"
            "mingw-w64-${TOOLCHAIN}-toolchain"
            "mingw-w64-${TOOLCHAIN}-MinHook"
            "mingw-w64-${TOOLCHAIN}-nsis"
            "mingw-w64-${TOOLCHAIN}-nodejs"
          )
          pacman -Syu --noconfirm "${dependencies[@]}"

      - name: Build
        shell: msys2 {0}
        env:
          BUILD_VERSION: "${{ github.ref_name }}"
          COMMIT: "${{ github.sha }}"
        run: |
          cmake \
            -B build \
            -G Ninja \
            -S . \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DSUNSHINE_ASSETS_DIR=assets \
            -DSUNSHINE_PUBLISHER_NAME="LegionGames" \
            -DSUNSHINE_PUBLISHER_WEBSITE="https://legiongames.ru" \
            -DSUNSHINE_PUBLISHER_ISSUE_URL="https://legiongames.ru"
          ninja -C build

      - name: Package
        shell: msys2 {0}
        run: |
          mkdir -p artifacts
          cd build
          cpack -G NSIS
          cpack -G ZIP
          mv ./cpack_artifacts/Sunshine.exe ../artifacts/Sunshine-Windows-AMD64-installer.exe
          mv ./cpack_artifacts/Sunshine.zip ../artifacts/Sunshine-Windows-AMD64-portable.zip

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sunshine-windows-amd64
          path: artifacts/
          if-no-files-found: error
